name: Devcontainer

on:
  pull_request:
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer.yml
      - Dockerfile
      - justfile

permissions:
  contents: read

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: ./actions/setup-tools
      - run: just build

  dev-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: ./actions/setup-tools
      - run: just-sh

  dev-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: ./actions/setup-tools
      - run: just-dev pull-dev-image

  markdownlint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: DavidAnson/markdownlint-cli2-action@8f3516061301755c97ff833a8e933f09282cc5b5
        with:
          globs: |
            **/*.md
            !repos/**
